### ISSUE TITLE
ExifReader NullReferenceException

### ISSUE THREAD

**Issue by vinhhrv** [JimBobSquarePants/ImageSharp#175]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
{System.NullReferenceException: Object reference not set to an instance of an object.
   at ImageSharp.ExifReader.ToString(Byte[] data)
   at ImageSharp.ExifReader.Read(Byte[] data)
   at ImageSharp.ExifProfile.InitializeValues()
   at ImageSharp.ExifProfile.GetValue(ExifTag tag)
   at ImageSharp.ExifProfile.Sync(ImageMetaData metaData)
   at ImageSharp.Formats.JpegEncoderCore.WriteProfiles[TColor](Image`1 image)
   at ImageSharp.Formats.JpegEncoderCore.Encode[TColor](Image`1 image, Stream stream)
   at ImageSharp.Formats.JpegEncoder.Encode[TColor](Image`1 image, Stream stream, IEncoderOptions options)
   at ImageSharp.Image`1.Save(Stream stream, IImageEncoder encoder, IEncoderOptions options)
### Steps to Reproduce
```
using(var outStream = new MemoryStream())
using (var file = File.OpenRead("files/jpeg_bug3.jpg"))
using (var image = Image.Load(file))
{
    ResizeOptions opt = new ResizeOptions();
    opt.Mode = ResizeMode.Max;
    opt.Size = new Size(100,100);
    image.Resize(opt)
                         .Save(outStream);
}
```
### System Configuration

- ImageSharp version: 1.0.0-alpha5-00071
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): win10
- .NET Framework version: netcoreapp1.0
- Additional information:

Attach File

![jpeg_bug3](https://cloud.githubusercontent.com/assets/769541/25064842/b0e02d90-222d-11e7-9eec-d062c436c2eb.jpg)

**Comment by dlemstra** [comment]
Thanks for the detailed bug report. I'll take a look at this since it will probably also affect Magick.NET.
