### ISSUE TITLE
image.DrawText causes a method not found exception

### ISSUE THREAD

**Issue by MaddoScientisto** [JimBobSquarePants/ImageSharp#177]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

usage of image.DrawText causes a method not found exception, a described in the log posted further down

### Steps to Reproduce
```
            var fff = FontCollection.SystemFonts.Find("Verdana");

            var font = new Font(fff, 8f, FontStyle.Regular);

            image.DrawText("test", font, Color.Black, new Vector2(200, 200));
```

### System Configuration

- ImageSharp version: 1.0.0-alpha5-00086 
- Other ImageSharp packages and versions: imagesharp.drawing: 1.0.0-alpha5-00080
- - sixlabor.fonts: 0.1.0-alpha0007
- Environment (Operating system, version and so on): windows 10 64 bit
- - Build settings: x64
- .NET Framework version: 4.6
- Additional information:

```System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'Void SixLabors.Fonts.FontSpan..ctor(SixLabors.Fonts.Font, System.Numerics.Vector2)'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at ImageSharp.ImageExtensions.DrawText[TColor](Image`1 source, String text, Font font, IBrush`1 brush, IPen`1 pen, Vector2 location, TextGraphicsOptions options)
   at ImageSharp.ImageExtensions.DrawText[TColor](Image`1 source, String text, Font font, TColor color, Vector2 location)
   at CatalogLib.ImgSharpCreator.SetExtraText(Image image) in E:\dev\vs\Catalog\CatalogLib\ImgSharpCreator.cs:line 115
   at CatalogLib.ImgSharpCreator.Start(FileInfo workFile) in E:\dev\vs\Catalog\CatalogLib\ImgSharpCreator.cs:line 85
   at WPFCatalog.MainWindowViewModel.Start() in E:\dev\vs\Catalog\WPFCatalog\MainWindowViewModel.cs:line 89

```

**Comment by tocsoft** [comment]
this looks like its actually a nuget restore issue, and the way it handles pre-release dependencies, i've bumped the version numbers an hopefully that should resolve it

You will want to make sure your on
ImageSharp 1.0.0-alpha6-00049 and ImageSharp.Drawing 1.0.0-alpha6-00010 they should pull in the correct versions of SixLabors.Fonts &  SixLabors.Shapes and allow everything to just work.

**Comment by MaddoScientisto** [comment]
That didn't solve it, now the error is:
```System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'Void SixLabors.Fonts.IGlyphRenderer.BeginGlyph(System.Numerics.Vector2)'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at ImageSharp.ImageExtensions.DrawText[TColor](Image`1 source, String text, Font font, IBrush`1 brush, IPen`1 pen, Vector2 location, TextGraphicsOptions options)
   at ImageSharp.ImageExtensions.DrawText[TColor](Image`1 source, String text, Font font, TColor color, Vector2 location)
   at CatalogLib.ImgSharpCreator.SetExtraText(Image image) in E:\dev\vs\Catalog\CatalogLib\ImgSharpCreator.cs:line 120
   at CatalogLib.ImgSharpCreator.Start(FileInfo workFile) in E:\dev\vs\Catalog\CatalogLib\ImgSharpCreator.cs:line 87
   at WPFCatalog.MainWindowViewModel.Start() in E:\dev\vs\Catalog\WPFCatalog\MainWindowViewModel.cs:line 89
```

**Comment by tocsoft** [comment]
looks like your build isn't using the latest version of SixLabors.Fonts as that method is defiantly there.

**Comment by MaddoScientisto** [comment]
Yep, turns out that I had the library also in another project and it was messing everything up, removing it fixed everything
