### ISSUE TITLE
ICC : Culture is not supported

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageSharp#261]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce

When attempting to decode and encode **turtle.jpg** from the solution tests the following exception is thrown:

```
System.Globalization.CultureNotFoundException : Culture is not supported.
Parameter name: name
ar- is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at ImageSharp.IccDataReader.ReadMultiLocalizedUnicodeTagDataEntry() in C:\development\github\ImageSharp\src\ImageSharp\MetaData\Profiles\ICC\DataReader\IccDataReader.TagDataEntry.cs:line 485
   at ImageSharp.IccDataReader.ReadTagDataEntry(IccTagTableEntry info) in C:\development\github\ImageSharp\src\ImageSharp\MetaData\Profiles\ICC\DataReader\IccDataReader.TagDataEntry.cs:line 52
   at ImageSharp.IccReader.ReadTagData(IccDataReader reader) in C:\development\github\ImageSharp\src\ImageSharp\MetaData\Profiles\ICC\IccReader.cs:line 102
   at ImageSharp.IccProfile.InitializeEntries() in C:\development\github\ImageSharp\src\ImageSharp\MetaData\Profiles\ICC\IccProfile.cs:line 189
   at ImageSharp.IccWriter.Write(IccProfile profile) in C:\development\github\ImageSharp\src\ImageSharp\MetaData\Profiles\ICC\IccWriter.cs:line 28
   at ImageSharp.Formats.JpegEncoderCore.WriteIccProfile(IccProfile iccProfile) in C:\development\github\ImageSharp\src\ImageSharp\Formats\Jpeg\JpegEncoderCore.cs:line 721
   at ImageSharp.Formats.JpegEncoderCore.Encode[TPixel](Image`1 image, Stream stream) in C:\development\github\ImageSharp\src\ImageSharp\Formats\Jpeg\JpegEncoderCore.cs:line 225
   at ImageSharp.Formats.JpegEncoder.Encode[TPixel](Image`1 image, Stream stream, IEncoderOptions options) in C:\development\github\ImageSharp\src\ImageSharp\Formats\Jpeg\JpegEncoder.cs:line 24
   at ImageSharp.Image`1.Save(Stream stream, IImageEncoder encoder, IEncoderOptions options) in C:\development\github\ImageSharp\src\ImageSharp\Image\Image{TPixel}.cs:line 241
   at ImageSharp.Tests.GeneralFormatTests.DecodeThenEncodeImageFromStreamShouldSucceed() in C:\development\github\ImageSharp\tests\ImageSharp.Tests\Formats\GeneralFormatTests.cs:line 47
```

If we attempt to normalize the value by trimming off the end character `-` the following exception is thrown,

```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at.ImageSharp.IccDataWriter.WriteMultiLocalizedUnicodeTagDataEntry(IccMultiLocalizedUnicodeTagDataEntry value) in C:\development\github\ImageSharp\src\ImageSharp\MetaData\Profiles\ICC\DataWriter\IccDataWriter.TagDataEntry.cs:line 552
   at ImageSharp.IccDataWriter.WriteTagDataEntry(IccTagDataEntry entry) in C:\development\github\ImageSharp\src\ImageSharp\MetaData\Profiles\ICC\DataWriter\IccDataWriter.TagDataEntry.cs:line 73
   at ImageSharp.IccDataWriter.WriteTagDataEntry(IccTagDataEntry data, IccTagTableEntry& table) in C:\development\github\ImageSharp\src\ImageSharp\MetaData\Profiles\ICC\DataWriter\IccDataWriter.TagDataEntry.cs:line 22
   at ImageSharp.IccWriter.WriteTagData(IccDataWriter writer, List`1 entries) in C:\development\github\ImageSharp\src\ImageSharp\MetaData\Profiles\ICC\IccWriter.cs:line 89
   at ImageSharp.IccWriter.Write(IccProfile profile) in C:\development\github\ImageSharp\src\ImageSharp\MetaData\Profiles\ICC\IccWriter.cs:line 28
   at ImageSharp.Formats.JpegEncoderCore.WriteIccProfile(IccProfile iccProfile) in C:\development\github\ImageSharp\src\ImageSharp\Formats\Jpeg\JpegEncoderCore.cs:line 721
   at ImageSharp.Formats.JpegEncoderCore.Encode[TPixel](Image`1 image, Stream stream) in C:\development\github\ImageSharp\src\ImageSharp\Formats\Jpeg\JpegEncoderCore.cs:line 225
   at ImageSharp.Formats.JpegEncoder.Encode[TPixel](Image`1 image, Stream stream, IEncoderOptions options) in C:\development\github\ImageSharp\src\ImageSharp\Formats\Jpeg\JpegEncoder.cs:line 24
   at ImageSharp.Image`1.Save(Stream stream, IImageEncoder encoder, IEncoderOptions options) in C:\development\github\ImageSharp\src\ImageSharp\Image\Image{TPixel}.cs:line 241
   at ImageSharp.Tests.GeneralFormatTests.DecodeThenEncodeImageFromStreamShouldSucceed() in C:\development\github\ImageSharp\tests\ImageSharp.Tests\Formats\GeneralFormatTests.cs:line 47
```

@JBildstein Would it be possible for you to have a look at this? I bow down to your far superior knowledge on the subject

### System Configuration

- ImageSharp version: **1.0.0-alpha9-00152**
- Other ImageSharp packages and versions: **NA**
- Environment (Operating system, version and so on): **Win 10**
- .NET Framework version: **NA**
- Additional information: **NA**

**Comment by JBildstein** [comment]
of course, I already know where and why this happens but need to think about how to solve it best.

**Comment by JimBobSquarePants** [comment]
Thank you! Very much appreciated!
