### ISSUE TITLE
System.AccessViolationException when cropping some images

### ISSUE THREAD

**Issue by lukemurray** [JimBobSquarePants/ImageSharp#29]
Hi I am using this library to crop sections out of a larger image. Thousands of them. Every so often it hits an image I try to crop and I get this error

```Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: 
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ImageSharp.Processors.CropProcessor`2.<>c__DisplayClass0_1.<Apply>b__0(Int32 y)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.Tasks.TaskReplicator.Replica.<>c.<.ctor>b__4_0(Object s)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ImageSharp.Processors.CropProcessor`2.<>c__DisplayClass0_1.<Apply>b__0(Int32 y)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.Tasks.TaskReplicator.Replica.<>c.<.ctor>b__4_0(Object s)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ImageSharp.Processors.CropProcessor`2.<>c__DisplayClass0_1.<Apply>b__0(Int32 y)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.Tasks.TaskReplicator.Replica.<>c.<.ctor>b__4_0(Object s)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Based on `CropProcessor` I assume it is when cropping not when reading the image. My pseudo code is like this

```
for each image in images // there is > 10,000
    image = new Image(path)
    for each section in sections // from another file I load, basically bounding boxes within the image
        image.Crop(...).Save(newFilePath)
```

Thanks

**Comment by lukemurray** [comment]
More info. if I load the image every time before cropping it doesn't error.
```for each image in images // there is > 10,000
    for each section in sections // from another file I load, basically bounding boxes within the image
        image = new Image(path)
        image.Crop(...).Save(newFilePath)```

But why would it work for a few thousand images previously and then fail, and always on the same image.

**Comment by lukemurray** [comment]
Actually the comment above, that change, run much slower (it loads the image many more times), it did get past some files that failed previously but eventually did fail with the same original exception.

**Comment by lukemurray** [comment]
Adding to that. This is on Ubuntu 16.04 running .NET core 1.1

**Comment by JimBobSquarePants** [comment]
Hi @lukemurray 

Would it be possible to post an actual code sample. I want to be sure you are not trying to lock an already locked image. 

Cheers

James

**Comment by lukemurray** [comment]
Sure

```C#
foreach (var labelledImage in annotatedFullImages)
{
    // I build some strings here relating to output filename
    var outputDir = ....
    using (var input = File.OpenRead(labelledImage.image_path))
    {
        var seenRects = new HashSet<string>();
        
        var i = 0;
        foreach (var obj in labelledImage.rects)
        {
            var image = new Image(input);
            // only create the directory if we have obj
            if (!Directory.Exists(outputDir))
                Directory.CreateDirectory(outputDir);

            // prevent creating too many images of the same thing is they do not move
            var objKey = $"{obj.x1}{obj.x2}{obj.y1}{obj.y2}";
            if (seenRects.Contains(objKey))
                continue;
            seenRects.Add(objKey);
            
            i += 1;
            var outputPath = Path.Combine(outputDir, i.ToString("0000") + ".jpg");

            var w = (int)(obj.x2 - obj.x1) + boxPadding;
            var h = (int)(obj.y2 - obj.y1) + boxPadding;

            if (!File.Exists(outputPath))
                using (var output = File.OpenWrite(outputPath))
                {
                    var rect = new Rectangle();
                    rect.X = (int)obj.x1 - (int)(boxPadding / 2);
                    rect.Y = (int)obj.y1 - (int)(boxPadding / 2);
                    rect.Width = w;
                    rect.Height = h;
                    
                    image.Crop(w, h, rect).Save(output);
                }
        }
    }
}
```

**Comment by JimBobSquarePants** [comment]
Hmmm... Nothing seems amiss there that I can see. 

I think what is most likely happening is that it's attempting to crop with a rectangle outwith the bounds of the image. Maybe a bounds check gone wrong? 

The best way to ascertain what is happening would be to download the source and attach a debugger. Without that it's going to be incredibly difficult for me to properly diagnose and fix the issue.

The place to look is the `PixelAccessor<TColor,TPacked>` indexer.

**Comment by lukemurray** [comment]
Ding! that was it thanks. Sorry I missed that. It was sometimes cropping to outside of the image. Could it throw a better error for that?

**Comment by JimBobSquarePants** [comment]
It most certainly should, I just need to do it in a way that doesn't hurt performance. 

Realistically it should never hit the point you did though and input should be sanitized. Better sanitation of input is on my ever-growing todo list.
